### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by psi** [instructure-bridge/truss-cli#10]
Starting this just as a place to keep some thoughts. We have a few different possible debugging scenarios and I think it might be worth incorporating at least some into the CLI.

1. *Spinning up a "shell" pod*
    I have a `kube-shell` alias that directly creates a Pod to use as a general debugging container, that runs this `kubectl run --generator=run-pod/v1 shell-$(whoami)-$(random-id) --image-pull-policy="Always" --labels app=toolbox --rm -i --tty --image jdharrington/toolbox $@ -- /bin/bash`. This lets me test things outside the direct context of an existing pod, but lets me pass additional args to run in a specific namespace, as a service account, etc. I find this useful for things like 1) testing networking/rbac in and outside of istio (would be nice to have a simple flag to turn istio on or off for these), root access to vault, etc. It would probably be better to make these one-off Deployments rather than direct Pods, because draining nodes, by default, doesn't work for pods that aren't associated with a replication controller. We could maybe also have an operator that watches for these and reaps them if they get left orphaned.

   `truss shell <args>`

2. *Exec-ing into a running container*
    This is just a `kubectl exec`, so I don't know if there's any real value in providing a truss CLI convenience method, but maybe? The use case here is really interacting directly with the application in some way, like running a Rails console. An alternative here, which I've also done in the past, is to spin up an additional "cloned" pod, that wouldn't receive production traffic but otherwise mimics the environment. That lets you spin up a temporary Pod to run a Rails console or other application debugging without interfering with the live Pods. I think the ability to both of those things is probably desired.

   `truss shell pod <pod-name> <container-name>`
   `truss shell pod <pod-name> <container-name> --clone`

3. *Launching an additional debug container alongside a pod*
    https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container
    https://github.com/aylei/kubectl-debug

    The idea here is that your application containers should be relatively slim and not contain extraneous debugging utilities that aren't needed for normal operation, but that you may want to attach to running processes with tools like `strace` or debug networking issues from inside the same pod. This would likely use the same image as the shell pod discussed in #1, which would contain commonly used debugging utilities.

  `truss shell --debug pod <pod-name> <container-name>` or `truss shell --debug pod -l app=hello-world`.

4. *Launch a privileged debugging container*
    This would again use the same image as #1 and #3, but would launch an AWS SSM Agent container that can be connected to with `aws ssm start-session`. This should provide near-host level access with rich debugging utilities and could either be brought up on demand or could be left running at all times.

    `truss shell node <node-name-or-instance-id>`
    `truss shell node -l nodegroup=system`

5. *SSH to the underlying host itself*
   If we've done a reasonable job with observability and all of the above, this should not be a frequent requirement, but we should give ourselves the option. Since nodes are on private networks, this requires either proxying through a jumpbox or launching a PortForwardingSession via Systems Manager. If we find there are additional debugging tools that we want here, not included by default, we can install them via userdata scripts or start rolling our own customized base AMIs.

   `truss shell node --host <node-name-or-instance-id>`
   `truss shell node --host -l nodegroup=system`

**Comment by adamgoose** [comment]
Done?

**Comment by psi** [comment]
2/5 done, but probably good enough.
