### ISSUE TITLE
truss-cli shell does not stop the pod after exiting

### ISSUE THREAD

**Issue by CalKrug** [instructure-bridge/truss-cli#64]
When launching a shell with `truss-cli shell -e <env> -n <namespace> -s <serviceaccount>`, the pod does not exit after exiting the shell.

It looks like the shell container itself stops, but the istio container does not stop.  Using Ctrl-C will bring you back to your local prompt, but then you have to kill the shell pod manually using kubectl or k9s.

**Comment by psi** [comment]
Fixed in truss-cli v0.2.3
